### ISSUE TITLE
QOL on Banned User Pages

### ISSUE THREAD

**Issue by ghost** [Aevann1/rDrama#97]
![bannedUser](https://user-images.githubusercontent.com/88643009/141422394-56cfd47f-910c-4995-97b1-6e72ab0d6b69.PNG)

I'd love it if "@UserNameHere", the user that gave out the banning was a link, as well as "/post/12345566" being wrapped in an <a> to provide a link to the post.

https://github.com/Aevann1/Drama/blob/master/files/templates/userpage.html#L110

Looks like banned reason is just stored as a simple string, where if we could add columns for banned users where we have reason(in this case Ban Award), ban_user, and ban_post(url for the post), then we could accomplish this.

**Comment by DuffyElmer** [comment]
Seconded. The more people have an opportunity to see [USER WAS BANNED FOR
THIS POST] the better.

Duffy Elmer
(m) 830.570.4288

**Comment by TheCaringCleaner** [comment]
I did a quick [PR](https://github.com/Aevann1/Drama/pull/103) to allow *normal* ban messages to be linked, @Aevann1 just merged it :+1: It wont work for ban awards and linking to the user though.

> Looks like banned reason is just stored as a simple string, where if we could add columns for banned users where we have reason(in this case Ban Award), ban_user, and ban_post(url for the post), then we could accomplish this.

I think it would be awesome for the bans to be in their own table, via something like this:

```
user_id | banning_user_id | award_id | submission_id | comment_id |  reason  | length_days | unban_utc 
--------|-----------------|----------|---------------|------------|----------|-------------|-----------
 int    | int             | int      | int           | int        | varchar  | int         | int
        |                 | nullable | nullable      | nullable   | nullable |             | nullable
fk:users| fk:users        | fk:awards| fk:submissions| fk:comments|          |             |
```

Mainly because I think it would be funny to be able to query that table and be able to do shit like:

- leaderboard of most bullied (i.e. banned) users
- badges for users that gets bullied x amount of times

**Comment by Aevann1** [comment]
done king
